"""
Validation module for comparing model outputs to published CBO scores.

This module provides:
- Database of known CBO/JCT revenue estimates
- Comparison functions for accuracy analysis
- Validation reports
"""

from .cbo_scores import (
    KNOWN_SCORES,
    MIN_GENERIC_BASELINE_YEAR,
    CBOScore,
    describe_target_coverage,
    get_excluded_scores,
    get_score,
    get_scores_by_type,
    get_specialized_targets,
    get_validation_targets,
    list_available_policies,
    validation_shape,
)
from .compare import (
    AMT_VALIDATION_SCENARIOS_COMPARE,
    CAPITAL_GAINS_VALIDATION_SCENARIOS,
    CLIMATE_VALIDATION_SCENARIOS_COMPARE,
    CORPORATE_VALIDATION_SCENARIOS,
    ENFORCEMENT_VALIDATION_SCENARIOS_COMPARE,
    ESTATE_TAX_VALIDATION_SCENARIOS,
    INTERNATIONAL_VALIDATION_SCENARIOS_COMPARE,
    PAYROLL_TAX_VALIDATION_SCENARIOS,
    PHARMA_VALIDATION_SCENARIOS_COMPARE,
    PTC_VALIDATION_SCENARIOS_COMPARE,
    TAX_CREDIT_VALIDATION_SCENARIOS,
    TAX_EXPENDITURE_VALIDATION_SCENARIOS_COMPARE,
    TCJA_VALIDATION_SCENARIOS,
    TRADE_VALIDATION_SCENARIOS_COMPARE,
    ValidationResult,
    generate_validation_report,
    quick_validate,
    run_validation_suite,
    validate_all,
    validate_all_amt,
    validate_all_capital_gains,
    validate_all_climate,
    validate_all_corporate,
    validate_all_credits,
    validate_all_enforcement,
    validate_all_estate,
    validate_all_expenditures,
    validate_all_international,
    validate_all_payroll,
    validate_all_pharma,
    validate_all_pl119_21,
    validate_all_ptc,
    validate_all_tcja,
    validate_all_trade,
    # AMT validation
    validate_amt_policy,
    # Capital gains validation
    validate_capital_gains_policy,
    # Corporate tax validation
    validate_corporate_policy,
    # Tax credit validation
    validate_credit_policy,
    # Estate tax validation
    validate_estate_policy,
    # Tax expenditure validation
    validate_expenditure_policy,
    # Payroll tax validation
    validate_payroll_policy,
    validate_pl119_21_provision,
    validate_policy,
    # PTC validation
    validate_ptc_policy,
    # Sectoral module reconstructions (international/trade/pharma/enforcement/climate)
    validate_sectoral_policy,
    # TCJA validation
    validate_tcja_extension,
)
from .credibility import (
    ConfidenceBand,
    ResultCredibility,
    credibility_to_dict,
    estimate_uncertainty_dollars,
    format_band_caption,
    get_band_for_policy_type,
    get_band_for_preset_area,
    get_band_for_result,
    get_credibility_for_result,
    reset_confidence_cache,
)
from .holdout import (
    DEFAULT_HOLDOUT_PROTOCOL,
    HoldoutProtocol,
    category_holdout_status,
    evidence_type_for_entry,
    holdout_entries,
    holdout_status_for_entry,
    summarize_holdout_protocol,
    validation_role_for_entry,
)
from .loo import (
    LOOCase,
    LOOReport,
    LOOSuite,
    capital_gains_donor_matrix,
    run_leave_one_out,
)
from .preregistered import (
    PREREGISTERED_CASES,
    PreregisteredCase,
    assert_preregistered,
    get_case,
    live_cases,
    manifest_problems,
    summarize_preregistration,
)
from .provenance import (
    LINE_ITEM,
    MODEL_ESTIMATE,
    NON_PUBLISHED_BENCHMARK_IDS,
    NON_PUBLISHED_DISTRIBUTIONAL_BENCHMARKS,
    PROVENANCE_LEVELS,
    SECONDHAND,
    UNCLASSIFIED,
    classify_provenance,
    is_round_hundred_scale,
)
from .scorecard import (
    DEFAULT_RUNNERS,
    GENERIC_CATEGORY,
    ScorecardEntry,
    ScorecardSummary,
    cached_default_scorecard,
    compute_scorecard,
    reset_scorecard_cache,
    scorecard_to_dict,
)

__all__ = [
    'AMT_VALIDATION_SCENARIOS_COMPARE',
    'CAPITAL_GAINS_VALIDATION_SCENARIOS',
    'CLIMATE_VALIDATION_SCENARIOS_COMPARE',
    'CORPORATE_VALIDATION_SCENARIOS',
    'DEFAULT_HOLDOUT_PROTOCOL',
    'DEFAULT_RUNNERS',
    'ENFORCEMENT_VALIDATION_SCENARIOS_COMPARE',
    'ESTATE_TAX_VALIDATION_SCENARIOS',
    'GENERIC_CATEGORY',
    'INTERNATIONAL_VALIDATION_SCENARIOS_COMPARE',
    'KNOWN_SCORES',
    'LINE_ITEM',
    'MIN_GENERIC_BASELINE_YEAR',
    'MODEL_ESTIMATE',
    'NON_PUBLISHED_BENCHMARK_IDS',
    'NON_PUBLISHED_DISTRIBUTIONAL_BENCHMARKS',
    'PAYROLL_TAX_VALIDATION_SCENARIOS',
    'PHARMA_VALIDATION_SCENARIOS_COMPARE',
    'PREREGISTERED_CASES',
    'PROVENANCE_LEVELS',
    'PTC_VALIDATION_SCENARIOS_COMPARE',
    'SECONDHAND',
    'TAX_CREDIT_VALIDATION_SCENARIOS',
    'TAX_EXPENDITURE_VALIDATION_SCENARIOS_COMPARE',
    'TCJA_VALIDATION_SCENARIOS',
    'TRADE_VALIDATION_SCENARIOS_COMPARE',
    'UNCLASSIFIED',
    'CBOScore',
    'ConfidenceBand',
    'HoldoutProtocol',
    'LOOCase',
    'LOOReport',
    'LOOSuite',
    'PreregisteredCase',
    'ResultCredibility',
    'ScorecardEntry',
    'ScorecardSummary',
    'ValidationResult',
    'assert_preregistered',
    'cached_default_scorecard',
    'capital_gains_donor_matrix',
    'category_holdout_status',
    'classify_provenance',
    'compute_scorecard',
    'credibility_to_dict',
    'describe_target_coverage',
    'estimate_uncertainty_dollars',
    'evidence_type_for_entry',
    'format_band_caption',
    'generate_validation_report',
    'get_band_for_policy_type',
    'get_band_for_preset_area',
    'get_band_for_result',
    'get_case',
    'get_credibility_for_result',
    'get_excluded_scores',
    'get_score',
    'get_scores_by_type',
    'get_specialized_targets',
    'get_validation_targets',
    'holdout_entries',
    'holdout_status_for_entry',
    'is_round_hundred_scale',
    'list_available_policies',
    'live_cases',
    'manifest_problems',
    'quick_validate',
    'reset_confidence_cache',
    'reset_scorecard_cache',
    'run_leave_one_out',
    'run_validation_suite',
    'scorecard_to_dict',
    'summarize_holdout_protocol',
    'summarize_preregistration',
    'validate_all',
    'validate_all_amt',
    'validate_all_capital_gains',
    'validate_all_climate',
    'validate_all_corporate',
    'validate_all_credits',
    'validate_all_enforcement',
    'validate_all_estate',
    'validate_all_expenditures',
    'validate_all_international',
    'validate_all_payroll',
    'validate_all_pharma',
    'validate_all_pl119_21',
    'validate_all_ptc',
    'validate_all_tcja',
    'validate_all_trade',
    'validate_amt_policy',
    'validate_capital_gains_policy',
    'validate_corporate_policy',
    'validate_credit_policy',
    'validate_estate_policy',
    'validate_expenditure_policy',
    'validate_payroll_policy',
    'validate_pl119_21_provision',
    'validate_policy',
    'validate_ptc_policy',
    'validate_sectoral_policy',
    'validate_tcja_extension',
    'validation_role_for_entry',
    'validation_shape',
]

