"""
CBO-Style Fiscal Policy Scoring Model

A comprehensive framework for analyzing fiscal policy proposals
using Congressional Budget Office methodology.
"""

from .amt import (
    AMT_EXEMPTIONS_TCJA,
    AMT_EXEMPTIONS_TCJA_EXTENDED,
    AMT_RATES,
    AMT_VALIDATION_SCENARIOS,
    BASELINE_AMT_DATA,
    CBO_AMT_ESTIMATES,
    CORPORATE_AMT,
    AMTPolicy,
    AMTType,
    create_amt_rate_change,
    create_extend_tcja_amt_relief,
    create_increase_amt_exemption,
    create_repeal_corporate_amt,
    create_repeal_individual_amt,
    estimate_amt_revenue,
)
from .baseline import BaselineProjection, CBOBaseline
from .corporate import (
    BASELINE_CORPORATE_REVENUE_BILLIONS,
    CURRENT_CORPORATE_RATE,
    CorporateTaxPolicy,
    create_biden_corporate_proposal,
    create_biden_corporate_rate_only,
    create_corporate_rate_change,
    create_republican_corporate_cut,
    create_tcja_corporate_repeal,
    estimate_corporate_rate_revenue,
)
from .credits import (
    BASELINE_CREDIT_COSTS,
    CREDIT_VALIDATION_SCENARIOS,
    CTC_CURRENT_LAW,
    EITC_CURRENT_LAW,
    CreditType,
    TaxCreditPolicy,
    create_biden_ctc_2021,
    create_biden_eitc_childless,
    create_ctc_expansion,
    create_ctc_permanent_extension,
    create_eitc_expansion,
    estimate_credit_cost,
)
from .distribution import (
    DECILE_THRESHOLDS_2024,
    JCT_DOLLAR_BRACKETS,
    QUINTILE_THRESHOLDS_2024,
    TOP_INCOME_THRESHOLDS_2024,
    DistributionalAnalysis,
    DistributionalEngine,
    DistributionalResult,
    IncomeGroup,
    IncomeGroupType,
    format_distribution_table,
    generate_winners_losers_summary,
)
from .economics import DynamicEffects, EconomicConditions, EconomicModel
from .exceptions import (
    BaselineStaleError,
    DataSourceError,
    FiscalModelError,
    FREDUnavailableError,
    PolicyValidationError,
    ScoringBoundsError,
)
from .estate import (
    BASELINE_ESTATE_DATA,
    CBO_ESTATE_ESTIMATES,
    CURRENT_ESTATE_TAX_RATE,
    ESTATE_TAX_EXEMPTIONS,
    ESTATE_VALIDATION_SCENARIOS,
    EstateTaxPolicy,
    EstateTaxScenario,
    create_biden_estate_proposal,
    create_eliminate_estate_tax,
    create_estate_exemption_change,
    create_estate_rate_change,
    create_tcja_estate_extension,
    create_warren_estate_proposal,
    estimate_estate_revenue,
)
from .payroll import (
    CBO_PAYROLL_ESTIMATES,
    MEDICARE_PARAMS,
    NIIT_PARAMS,
    PAYROLL_VALIDATION_SCENARIOS,
    SOCIAL_SECURITY_PARAMS,
    PayrollTaxPolicy,
    PayrollTaxType,
    create_biden_payroll_proposal,
    create_expand_niit,
    create_medicare_rate_increase,
    create_ss_cap_90_percent,
    create_ss_donut_hole,
    create_ss_eliminate_cap,
    create_ss_rate_increase,
    estimate_payroll_revenue,
)
from .policies import (
    CapitalGainsPolicy,
    Policy,
    PolicyPackage,
    PolicyType,
    SpendingPolicy,
    TaxPolicy,
    TransferPolicy,
    create_income_tax_cut,
    create_new_tax_credit,
    create_spending_increase,
)
from .ptc import (
    BASELINE_PTC_COSTS,
    CBO_PTC_ESTIMATES,
    ENHANCED_PTC_CAPS,
    FPL_2025,
    MARKETPLACE_DATA,
    ORIGINAL_ACA_CAPS,
    PTC_VALIDATION_SCENARIOS,
    PremiumTaxCreditPolicy,
    PTCScenario,
    create_expand_ptc_eligibility,
    create_extend_enhanced_ptc,
    create_let_enhanced_expire,
    create_lower_premium_cap,
    create_repeal_ptc,
    estimate_ptc_cost,
    get_fpl,
)
from .reporting import BudgetReport
from .scoring import FiscalPolicyScorer, ScoringResult
from .tax_expenditures import (
    JCT_TAX_EXPENDITURES,
    REFORM_ESTIMATES,
    TAX_EXPENDITURE_VALIDATION_SCENARIOS,
    TaxExpenditurePolicy,
    TaxExpenditureType,
    create_cap_charitable_deduction,
    create_cap_employer_health_exclusion,
    create_cap_retirement_contributions,
    create_eliminate_like_kind_exchange,
    create_eliminate_mortgage_deduction,
    create_eliminate_salt_deduction,
    create_eliminate_step_up_basis,
    create_repeal_salt_cap,
    estimate_expenditure_revenue,
    get_all_expenditure_estimates,
)
from .tcja import (
    TCJA_COMPONENTS,
    TCJAComponent,
    TCJAExtensionPolicy,
    create_tcja_extension,
    create_tcja_repeal_salt_cap,
    estimate_tcja_extension_cost,
    get_tcja_component_summary,
)
from .uncertainty import UncertaintyAnalysis

__version__ = "1.0.0"
__all__ = [
    "AMT_EXEMPTIONS_TCJA",
    "AMT_EXEMPTIONS_TCJA_EXTENDED",
    "AMT_RATES",
    "AMT_VALIDATION_SCENARIOS",
    "BASELINE_AMT_DATA",
    "BASELINE_CORPORATE_REVENUE_BILLIONS",
    "BASELINE_CREDIT_COSTS",
    "BASELINE_ESTATE_DATA",
    "BASELINE_PTC_COSTS",
    "CBO_AMT_ESTIMATES",
    "CBO_ESTATE_ESTIMATES",
    "CBO_PAYROLL_ESTIMATES",
    "CBO_PTC_ESTIMATES",
    "CORPORATE_AMT",
    "CREDIT_VALIDATION_SCENARIOS",
    "CTC_CURRENT_LAW",
    "CURRENT_CORPORATE_RATE",
    "CURRENT_ESTATE_TAX_RATE",
    "DECILE_THRESHOLDS_2024",
    "EITC_CURRENT_LAW",
    "ENHANCED_PTC_CAPS",
    "ESTATE_TAX_EXEMPTIONS",
    "ESTATE_VALIDATION_SCENARIOS",
    "FPL_2025",
    "JCT_DOLLAR_BRACKETS",
    "JCT_TAX_EXPENDITURES",
    "MARKETPLACE_DATA",
    "MEDICARE_PARAMS",
    "NIIT_PARAMS",
    "ORIGINAL_ACA_CAPS",
    "PAYROLL_VALIDATION_SCENARIOS",
    "PTC_VALIDATION_SCENARIOS",
    "QUINTILE_THRESHOLDS_2024",
    "REFORM_ESTIMATES",
    "SOCIAL_SECURITY_PARAMS",
    "TAX_EXPENDITURE_VALIDATION_SCENARIOS",
    "TCJA_COMPONENTS",
    "TOP_INCOME_THRESHOLDS_2024",
    # AMT
    "AMTPolicy",
    "AMTType",
    "BaselineProjection",
    "BaselineStaleError",
    "BudgetReport",
    "CBOBaseline",
    "CapitalGainsPolicy",
    # Corporate tax
    "CorporateTaxPolicy",
    "CreditType",
    "DataSourceError",
    "DistributionalAnalysis",
    # Distributional Analysis
    "DistributionalEngine",
    "DistributionalResult",
    "DynamicEffects",
    "EconomicConditions",
    "EconomicModel",
    # Estate tax
    "EstateTaxPolicy",
    "EstateTaxScenario",
    "FREDUnavailableError",
    "FiscalModelError",
    "FiscalPolicyScorer",
    "IncomeGroup",
    "IncomeGroupType",
    "PTCScenario",
    # Payroll tax
    "PayrollTaxPolicy",
    "PayrollTaxType",
    "Policy",
    "PolicyPackage",
    "PolicyType",
    "PolicyValidationError",
    # Premium Tax Credits
    "PremiumTaxCreditPolicy",
    "ScoringBoundsError",
    "ScoringResult",
    "SpendingPolicy",
    "TCJAComponent",
    # TCJA extension
    "TCJAExtensionPolicy",
    # Tax credits
    "TaxCreditPolicy",
    # Tax Expenditures
    "TaxExpenditurePolicy",
    "TaxExpenditureType",
    "TaxPolicy",
    "TransferPolicy",
    "UncertaintyAnalysis",
    "create_amt_rate_change",
    "create_biden_corporate_proposal",
    "create_biden_corporate_rate_only",
    "create_biden_ctc_2021",
    "create_biden_eitc_childless",
    "create_biden_estate_proposal",
    "create_biden_payroll_proposal",
    "create_cap_charitable_deduction",
    "create_cap_employer_health_exclusion",
    "create_cap_retirement_contributions",
    "create_corporate_rate_change",
    "create_ctc_expansion",
    "create_ctc_permanent_extension",
    "create_eitc_expansion",
    "create_eliminate_estate_tax",
    "create_eliminate_like_kind_exchange",
    "create_eliminate_mortgage_deduction",
    "create_eliminate_salt_deduction",
    "create_eliminate_step_up_basis",
    "create_estate_exemption_change",
    "create_estate_rate_change",
    "create_expand_niit",
    "create_expand_ptc_eligibility",
    "create_extend_enhanced_ptc",
    "create_extend_tcja_amt_relief",
    "create_income_tax_cut",
    "create_increase_amt_exemption",
    "create_let_enhanced_expire",
    "create_lower_premium_cap",
    "create_medicare_rate_increase",
    "create_new_tax_credit",
    "create_repeal_corporate_amt",
    "create_repeal_individual_amt",
    "create_repeal_ptc",
    "create_repeal_salt_cap",
    "create_republican_corporate_cut",
    "create_spending_increase",
    "create_ss_cap_90_percent",
    "create_ss_donut_hole",
    "create_ss_eliminate_cap",
    "create_ss_rate_increase",
    "create_tcja_corporate_repeal",
    "create_tcja_estate_extension",
    "create_tcja_extension",
    "create_tcja_repeal_salt_cap",
    "create_warren_estate_proposal",
    "estimate_amt_revenue",
    "estimate_corporate_rate_revenue",
    "estimate_credit_cost",
    "estimate_estate_revenue",
    "estimate_expenditure_revenue",
    "estimate_payroll_revenue",
    "estimate_ptc_cost",
    "estimate_tcja_extension_cost",
    "format_distribution_table",
    "generate_winners_losers_summary",
    "get_all_expenditure_estimates",
    "get_fpl",
    "get_tcja_component_summary",
]

