"""Values tags for the Build catalog — GENERATED, do not edit by hand.

Regenerate with::

    python scripts/derive_policy_tags.py

Schema and enums live in ``fiscal_model/preset_ids.py``; the derivation
and its bands are documented in ``scripts/derive_policy_tags.py``;
hand-set values live in ``fiscal_model/data_files/policy_tags_overrides.yaml``.

``TAG_SOURCES`` records where each tag came from, so the UI can
distinguish a measured tag from an asserted one:

* ``engine:<path>``  - the distribution engine produced a quintile table
* ``fallback:<fam>`` - progressivity.py's documented incidence family
* ``not_modeled:*``  - the app declines to assert a progressivity
* ``derived:*``      - read off the catalog flags / the model's deficit sign
* ``override``       - set by hand in the overrides file, with a note
"""

from __future__ import annotations

POLICY_TAGS: dict[str, dict[str, str]] = {
    'tcja-full-extension': {
        'direction': 'cut_revenue',
        'progressivity': 'regressive',
        'govt_size': 'shrink',
        'base': 'individual',
        'generational': 'current',
    },
    'tcja-extension-no-salt-cap': {
        'direction': 'cut_revenue',
        'progressivity': 'regressive',
        'govt_size': 'shrink',
        'base': 'individual',
        'generational': 'current',
    },
    'tcja-rates-only': {
        'direction': 'cut_revenue',
        'progressivity': 'regressive',
        'govt_size': 'shrink',
        'base': 'individual',
        'generational': 'current',
    },
    'corporate-28pct': {
        'direction': 'raise_revenue',
        'progressivity': 'progressive',
        'govt_size': 'grow',
        'base': 'corporate',
        'generational': 'mixed',
    },
    'corporate-15pct': {
        'direction': 'cut_revenue',
        'progressivity': 'regressive',
        'govt_size': 'shrink',
        'base': 'corporate',
        'generational': 'mixed',
    },
    'ctc-expansion-2021': {
        'direction': 'add_spending',
        'progressivity': 'strong_progressive',
        'govt_size': 'grow',
        'base': 'transfer',
        'generational': 'mixed',
    },
    'ctc-extension': {
        'direction': 'add_spending',
        'progressivity': 'progressive',
        'govt_size': 'grow',
        'base': 'transfer',
        'generational': 'mixed',
    },
    'eitc-childless-expansion': {
        'direction': 'add_spending',
        'progressivity': 'strong_progressive',
        'govt_size': 'grow',
        'base': 'transfer',
        'generational': 'current',
    },
    'estate-extend-tcja': {
        'direction': 'cut_revenue',
        'progressivity': 'regressive',
        'govt_size': 'shrink',
        'base': 'estate',
        'generational': 'mixed',
    },
    'estate-exemption-3-5m': {
        'direction': 'raise_revenue',
        'progressivity': 'strong_progressive',
        'govt_size': 'grow',
        'base': 'estate',
        'generational': 'mixed',
    },
    'estate-repeal': {
        'direction': 'cut_revenue',
        'progressivity': 'regressive',
        'govt_size': 'shrink',
        'base': 'estate',
        'generational': 'mixed',
    },
    'ss-cap-90pct': {
        'direction': 'raise_revenue',
        'progressivity': 'strong_progressive',
        'govt_size': 'grow',
        'base': 'payroll',
        'generational': 'future',
    },
    'ss-donut-250k': {
        'direction': 'raise_revenue',
        'progressivity': 'strong_progressive',
        'govt_size': 'grow',
        'base': 'payroll',
        'generational': 'future',
    },
    'ss-cap-eliminate': {
        'direction': 'raise_revenue',
        'progressivity': 'strong_progressive',
        'govt_size': 'grow',
        'base': 'payroll',
        'generational': 'future',
    },
    'niit-expand': {
        'direction': 'raise_revenue',
        'progressivity': 'strong_progressive',
        'govt_size': 'grow',
        'base': 'payroll',
        'generational': 'future',
    },
    'amt-extend-tcja-relief': {
        'direction': 'cut_revenue',
        'progressivity': 'not_modeled',
        'govt_size': 'shrink',
        'base': 'individual',
        'generational': 'current',
    },
    'amt-repeal-individual': {
        'direction': 'cut_revenue',
        'progressivity': 'not_modeled',
        'govt_size': 'shrink',
        'base': 'individual',
        'generational': 'current',
    },
    'amt-repeal-corporate': {
        'direction': 'cut_revenue',
        'progressivity': 'regressive',
        'govt_size': 'shrink',
        'base': 'corporate',
        'generational': 'mixed',
    },
    'aca-ptc-extend-enhanced': {
        'direction': 'add_spending',
        'progressivity': 'strong_progressive',
        'govt_size': 'grow',
        'base': 'transfer',
        'generational': 'current',
    },
    'aca-ptc-repeal': {
        'direction': 'cut_spending',
        'progressivity': 'regressive',
        'govt_size': 'shrink',
        'base': 'transfer',
        'generational': 'current',
    },
    'cap-employer-health-exclusion': {
        'direction': 'raise_revenue',
        'progressivity': 'neutral',
        'govt_size': 'grow',
        'base': 'individual',
        'generational': 'current',
    },
    'salt-cap-repeal': {
        'direction': 'cut_revenue',
        'progressivity': 'regressive',
        'govt_size': 'shrink',
        'base': 'individual',
        'generational': 'current',
    },
    'step-up-basis-eliminate': {
        'direction': 'raise_revenue',
        'progressivity': 'strong_progressive',
        'govt_size': 'grow',
        'base': 'individual',
        'generational': 'current',
    },
    'charitable-deduction-cap': {
        'direction': 'raise_revenue',
        'progressivity': 'strong_progressive',
        'govt_size': 'grow',
        'base': 'individual',
        'generational': 'current',
    },
    'top-rate-39-6': {
        'direction': 'raise_revenue',
        'progressivity': 'strong_progressive',
        'govt_size': 'grow',
        'base': 'individual',
        'generational': 'current',
    },
    'millionaire-surtax-5pp': {
        'direction': 'raise_revenue',
        'progressivity': 'strong_progressive',
        'govt_size': 'grow',
        'base': 'individual',
        'generational': 'current',
    },
    'middle-class-rate-cut-2pp': {
        'direction': 'cut_revenue',
        'progressivity': 'regressive',
        'govt_size': 'shrink',
        'base': 'individual',
        'generational': 'current',
    },
    'across-the-board-rate-cut-5pp': {
        'direction': 'cut_revenue',
        'progressivity': 'regressive',
        'govt_size': 'shrink',
        'base': 'individual',
        'generational': 'current',
    },
    'ultra-millionaire-surtax-3pp': {
        'direction': 'raise_revenue',
        'progressivity': 'strong_progressive',
        'govt_size': 'grow',
        'base': 'individual',
        'generational': 'current',
    },
    'top-rate-45': {
        'direction': 'raise_revenue',
        'progressivity': 'strong_progressive',
        'govt_size': 'grow',
        'base': 'individual',
        'generational': 'current',
    },
    'medicare-surcharge-2pp': {
        'direction': 'raise_revenue',
        'progressivity': 'strong_progressive',
        'govt_size': 'grow',
        'base': 'individual',
        'generational': 'current',
    },
    'gilti-reform': {
        'direction': 'raise_revenue',
        'progressivity': 'progressive',
        'govt_size': 'grow',
        'base': 'corporate',
        'generational': 'mixed',
    },
    'fdii-repeal': {
        'direction': 'raise_revenue',
        'progressivity': 'progressive',
        'govt_size': 'grow',
        'base': 'corporate',
        'generational': 'mixed',
    },
    'pillar-two-adoption': {
        'direction': 'raise_revenue',
        'progressivity': 'progressive',
        'govt_size': 'grow',
        'base': 'corporate',
        'generational': 'mixed',
    },
    'international-package': {
        'direction': 'raise_revenue',
        'progressivity': 'progressive',
        'govt_size': 'grow',
        'base': 'corporate',
        'generational': 'mixed',
    },
    'irs-enforcement-ira': {
        'direction': 'raise_revenue',
        'progressivity': 'strong_progressive',
        'govt_size': 'grow',
        'base': 'enforcement',
        'generational': 'current',
    },
    'irs-enforcement-double': {
        'direction': 'raise_revenue',
        'progressivity': 'strong_progressive',
        'govt_size': 'grow',
        'base': 'enforcement',
        'generational': 'current',
    },
    'irs-enforcement-high-income': {
        'direction': 'raise_revenue',
        'progressivity': 'strong_progressive',
        'govt_size': 'grow',
        'base': 'enforcement',
        'generational': 'current',
    },
    'drug-negotiation-expand': {
        'direction': 'cut_spending',
        'progressivity': 'not_modeled',
        'govt_size': 'shrink',
        'base': 'transfer',
        'generational': 'current',
    },
    'insulin-cap-universal': {
        'direction': 'cut_spending',
        'progressivity': 'not_modeled',
        'govt_size': 'shrink',
        'base': 'transfer',
        'generational': 'current',
    },
    'drug-reference-pricing': {
        'direction': 'cut_spending',
        'progressivity': 'not_modeled',
        'govt_size': 'shrink',
        'base': 'transfer',
        'generational': 'current',
    },
    'drug-reform-comprehensive': {
        'direction': 'cut_spending',
        'progressivity': 'not_modeled',
        'govt_size': 'shrink',
        'base': 'transfer',
        'generational': 'current',
    },
    'tariff-universal-10pct': {
        'direction': 'raise_revenue',
        'progressivity': 'regressive',
        'govt_size': 'grow',
        'base': 'consumption',
        'generational': 'current',
    },
    'tariff-china-60pct': {
        'direction': 'raise_revenue',
        'progressivity': 'regressive',
        'govt_size': 'grow',
        'base': 'consumption',
        'generational': 'current',
    },
    'tariff-auto-25pct': {
        'direction': 'raise_revenue',
        'progressivity': 'regressive',
        'govt_size': 'grow',
        'base': 'consumption',
        'generational': 'current',
    },
    'tariff-steel-aluminum-25pct': {
        'direction': 'raise_revenue',
        'progressivity': 'regressive',
        'govt_size': 'grow',
        'base': 'consumption',
        'generational': 'current',
    },
    'tariff-reciprocal': {
        'direction': 'raise_revenue',
        'progressivity': 'regressive',
        'govt_size': 'grow',
        'base': 'consumption',
        'generational': 'current',
    },
    'ira-clean-energy-repeal': {
        'direction': 'raise_revenue',
        'progressivity': 'progressive',
        'govt_size': 'shrink',
        'base': 'corporate',
        'generational': 'future',
    },
    'carbon-tax-50': {
        'direction': 'raise_revenue',
        'progressivity': 'regressive',
        'govt_size': 'grow',
        'base': 'consumption',
        'generational': 'future',
    },
    'carbon-tax-25': {
        'direction': 'raise_revenue',
        'progressivity': 'regressive',
        'govt_size': 'grow',
        'base': 'consumption',
        'generational': 'future',
    },
    'ev-credit-repeal': {
        'direction': 'raise_revenue',
        'progressivity': 'progressive',
        'govt_size': 'shrink',
        'base': 'individual',
        'generational': 'future',
    },
    'ira-clean-energy-extend': {
        'direction': 'cut_revenue',
        'progressivity': 'regressive',
        'govt_size': 'shrink',
        'base': 'corporate',
        'generational': 'future',
    },
}

TAG_SOURCES: dict[str, dict[str, str]] = {
    'tcja-full-extension': {
        'direction': 'derived:deficit_sign',
        'progressivity': 'engine:synthetic',
        'govt_size': 'derived:direction',
        'base': 'derived:policy_module',
        'generational': 'derived:policy_module',
    },
    'tcja-extension-no-salt-cap': {
        'direction': 'derived:deficit_sign',
        'progressivity': 'engine:synthetic',
        'govt_size': 'derived:direction',
        'base': 'derived:policy_module',
        'generational': 'derived:policy_module',
    },
    'tcja-rates-only': {
        'direction': 'derived:deficit_sign',
        'progressivity': 'engine:synthetic',
        'govt_size': 'derived:direction',
        'base': 'derived:policy_module',
        'generational': 'derived:policy_module',
    },
    'corporate-28pct': {
        'direction': 'derived:deficit_sign',
        'progressivity': 'engine:synthetic',
        'govt_size': 'derived:direction',
        'base': 'derived:policy_module',
        'generational': 'derived:policy_module',
    },
    'corporate-15pct': {
        'direction': 'derived:deficit_sign',
        'progressivity': 'engine:synthetic',
        'govt_size': 'derived:direction',
        'base': 'derived:policy_module',
        'generational': 'derived:policy_module',
    },
    'ctc-expansion-2021': {
        'direction': 'derived:deficit_sign',
        'progressivity': 'engine:microsim',
        'govt_size': 'derived:direction',
        'base': 'derived:policy_module',
        'generational': 'override',
    },
    'ctc-extension': {
        'direction': 'derived:deficit_sign',
        'progressivity': 'engine:microsim',
        'govt_size': 'derived:direction',
        'base': 'derived:policy_module',
        'generational': 'override',
    },
    'eitc-childless-expansion': {
        'direction': 'derived:deficit_sign',
        'progressivity': 'engine:microsim',
        'govt_size': 'derived:direction',
        'base': 'derived:policy_module',
        'generational': 'derived:policy_module',
    },
    'estate-extend-tcja': {
        'direction': 'derived:deficit_sign',
        'progressivity': 'fallback:estate',
        'govt_size': 'derived:direction',
        'base': 'derived:policy_module',
        'generational': 'derived:policy_module',
    },
    'estate-exemption-3-5m': {
        'direction': 'derived:deficit_sign',
        'progressivity': 'fallback:estate',
        'govt_size': 'derived:direction',
        'base': 'derived:policy_module',
        'generational': 'derived:policy_module',
    },
    'estate-repeal': {
        'direction': 'derived:deficit_sign',
        'progressivity': 'fallback:estate',
        'govt_size': 'derived:direction',
        'base': 'derived:policy_module',
        'generational': 'derived:policy_module',
    },
    'ss-cap-90pct': {
        'direction': 'derived:deficit_sign',
        'progressivity': 'fallback:payroll_above_cap',
        'govt_size': 'derived:direction',
        'base': 'derived:policy_module',
        'generational': 'derived:policy_module',
    },
    'ss-donut-250k': {
        'direction': 'derived:deficit_sign',
        'progressivity': 'fallback:payroll_above_cap',
        'govt_size': 'derived:direction',
        'base': 'derived:policy_module',
        'generational': 'derived:policy_module',
    },
    'ss-cap-eliminate': {
        'direction': 'derived:deficit_sign',
        'progressivity': 'fallback:payroll_above_cap',
        'govt_size': 'derived:direction',
        'base': 'derived:policy_module',
        'generational': 'derived:policy_module',
    },
    'niit-expand': {
        'direction': 'derived:deficit_sign',
        'progressivity': 'fallback:niit',
        'govt_size': 'derived:direction',
        'base': 'derived:policy_module',
        'generational': 'derived:policy_module',
    },
    'amt-extend-tcja-relief': {
        'direction': 'derived:deficit_sign',
        'progressivity': 'override',
        'govt_size': 'derived:direction',
        'base': 'derived:policy_module',
        'generational': 'derived:policy_module',
    },
    'amt-repeal-individual': {
        'direction': 'derived:deficit_sign',
        'progressivity': 'override',
        'govt_size': 'derived:direction',
        'base': 'derived:policy_module',
        'generational': 'derived:policy_module',
    },
    'amt-repeal-corporate': {
        'direction': 'derived:deficit_sign',
        'progressivity': 'fallback:corporate',
        'govt_size': 'derived:direction',
        'base': 'derived:policy_module',
        'generational': 'override',
    },
    'aca-ptc-extend-enhanced': {
        'direction': 'derived:deficit_sign',
        'progressivity': 'fallback:subsidy_repeal',
        'govt_size': 'derived:direction',
        'base': 'derived:policy_module',
        'generational': 'derived:policy_module',
    },
    'aca-ptc-repeal': {
        'direction': 'derived:deficit_sign',
        'progressivity': 'fallback:subsidy_repeal',
        'govt_size': 'derived:direction',
        'base': 'derived:policy_module',
        'generational': 'derived:policy_module',
    },
    'cap-employer-health-exclusion': {
        'direction': 'derived:deficit_sign',
        'progressivity': 'engine:synthetic',
        'govt_size': 'derived:direction',
        'base': 'derived:policy_module',
        'generational': 'derived:policy_module',
    },
    'salt-cap-repeal': {
        'direction': 'derived:deficit_sign',
        'progressivity': 'engine:microsim',
        'govt_size': 'derived:direction',
        'base': 'derived:policy_module',
        'generational': 'derived:policy_module',
    },
    'step-up-basis-eliminate': {
        'direction': 'derived:deficit_sign',
        'progressivity': 'engine:synthetic',
        'govt_size': 'derived:direction',
        'base': 'derived:policy_module',
        'generational': 'derived:policy_module',
    },
    'charitable-deduction-cap': {
        'direction': 'derived:deficit_sign',
        'progressivity': 'engine:synthetic',
        'govt_size': 'derived:direction',
        'base': 'derived:policy_module',
        'generational': 'derived:policy_module',
    },
    'top-rate-39-6': {
        'direction': 'derived:deficit_sign',
        'progressivity': 'engine:microsim',
        'govt_size': 'derived:direction',
        'base': 'derived:policy_module',
        'generational': 'derived:policy_module',
    },
    'millionaire-surtax-5pp': {
        'direction': 'derived:deficit_sign',
        'progressivity': 'engine:microsim',
        'govt_size': 'derived:direction',
        'base': 'derived:policy_module',
        'generational': 'derived:policy_module',
    },
    'middle-class-rate-cut-2pp': {
        'direction': 'derived:deficit_sign',
        'progressivity': 'engine:microsim',
        'govt_size': 'derived:direction',
        'base': 'derived:policy_module',
        'generational': 'derived:policy_module',
    },
    'across-the-board-rate-cut-5pp': {
        'direction': 'derived:deficit_sign',
        'progressivity': 'engine:microsim',
        'govt_size': 'derived:direction',
        'base': 'derived:policy_module',
        'generational': 'derived:policy_module',
    },
    'ultra-millionaire-surtax-3pp': {
        'direction': 'derived:deficit_sign',
        'progressivity': 'engine:microsim',
        'govt_size': 'derived:direction',
        'base': 'derived:policy_module',
        'generational': 'derived:policy_module',
    },
    'top-rate-45': {
        'direction': 'derived:deficit_sign',
        'progressivity': 'engine:microsim',
        'govt_size': 'derived:direction',
        'base': 'derived:policy_module',
        'generational': 'derived:policy_module',
    },
    'medicare-surcharge-2pp': {
        'direction': 'derived:deficit_sign',
        'progressivity': 'engine:microsim',
        'govt_size': 'derived:direction',
        'base': 'derived:policy_module',
        'generational': 'derived:policy_module',
    },
    'gilti-reform': {
        'direction': 'derived:deficit_sign',
        'progressivity': 'fallback:corporate',
        'govt_size': 'derived:direction',
        'base': 'derived:policy_module',
        'generational': 'derived:policy_module',
    },
    'fdii-repeal': {
        'direction': 'derived:deficit_sign',
        'progressivity': 'fallback:corporate',
        'govt_size': 'derived:direction',
        'base': 'derived:policy_module',
        'generational': 'derived:policy_module',
    },
    'pillar-two-adoption': {
        'direction': 'derived:deficit_sign',
        'progressivity': 'fallback:corporate',
        'govt_size': 'derived:direction',
        'base': 'derived:policy_module',
        'generational': 'derived:policy_module',
    },
    'international-package': {
        'direction': 'derived:deficit_sign',
        'progressivity': 'fallback:corporate',
        'govt_size': 'derived:direction',
        'base': 'derived:policy_module',
        'generational': 'derived:policy_module',
    },
    'irs-enforcement-ira': {
        'direction': 'derived:deficit_sign',
        'progressivity': 'fallback:compliance',
        'govt_size': 'derived:direction',
        'base': 'derived:policy_module',
        'generational': 'derived:policy_module',
    },
    'irs-enforcement-double': {
        'direction': 'derived:deficit_sign',
        'progressivity': 'fallback:compliance',
        'govt_size': 'derived:direction',
        'base': 'derived:policy_module',
        'generational': 'derived:policy_module',
    },
    'irs-enforcement-high-income': {
        'direction': 'derived:deficit_sign',
        'progressivity': 'fallback:compliance',
        'govt_size': 'derived:direction',
        'base': 'derived:policy_module',
        'generational': 'derived:policy_module',
    },
    'drug-negotiation-expand': {
        'direction': 'derived:deficit_sign',
        'progressivity': 'override',
        'govt_size': 'derived:direction',
        'base': 'derived:policy_module',
        'generational': 'override',
    },
    'insulin-cap-universal': {
        'direction': 'derived:deficit_sign',
        'progressivity': 'override',
        'govt_size': 'derived:direction',
        'base': 'derived:policy_module',
        'generational': 'override',
    },
    'drug-reference-pricing': {
        'direction': 'derived:deficit_sign',
        'progressivity': 'override',
        'govt_size': 'derived:direction',
        'base': 'derived:policy_module',
        'generational': 'override',
    },
    'drug-reform-comprehensive': {
        'direction': 'derived:deficit_sign',
        'progressivity': 'override',
        'govt_size': 'derived:direction',
        'base': 'derived:policy_module',
        'generational': 'override',
    },
    'tariff-universal-10pct': {
        'direction': 'derived:deficit_sign',
        'progressivity': 'fallback:consumption',
        'govt_size': 'derived:direction',
        'base': 'derived:policy_module',
        'generational': 'derived:policy_module',
    },
    'tariff-china-60pct': {
        'direction': 'derived:deficit_sign',
        'progressivity': 'fallback:consumption',
        'govt_size': 'derived:direction',
        'base': 'derived:policy_module',
        'generational': 'derived:policy_module',
    },
    'tariff-auto-25pct': {
        'direction': 'derived:deficit_sign',
        'progressivity': 'fallback:consumption',
        'govt_size': 'derived:direction',
        'base': 'derived:policy_module',
        'generational': 'derived:policy_module',
    },
    'tariff-steel-aluminum-25pct': {
        'direction': 'derived:deficit_sign',
        'progressivity': 'fallback:consumption',
        'govt_size': 'derived:direction',
        'base': 'derived:policy_module',
        'generational': 'derived:policy_module',
    },
    'tariff-reciprocal': {
        'direction': 'derived:deficit_sign',
        'progressivity': 'fallback:consumption',
        'govt_size': 'derived:direction',
        'base': 'derived:policy_module',
        'generational': 'derived:policy_module',
    },
    'ira-clean-energy-repeal': {
        'direction': 'derived:deficit_sign',
        'progressivity': 'fallback:credit_repeal',
        'govt_size': 'override',
        'base': 'override',
        'generational': 'override',
    },
    'carbon-tax-50': {
        'direction': 'derived:deficit_sign',
        'progressivity': 'fallback:consumption',
        'govt_size': 'derived:direction',
        'base': 'derived:policy_module',
        'generational': 'derived:policy_module',
    },
    'carbon-tax-25': {
        'direction': 'derived:deficit_sign',
        'progressivity': 'fallback:consumption',
        'govt_size': 'derived:direction',
        'base': 'derived:policy_module',
        'generational': 'derived:policy_module',
    },
    'ev-credit-repeal': {
        'direction': 'derived:deficit_sign',
        'progressivity': 'fallback:credit_repeal',
        'govt_size': 'override',
        'base': 'override',
        'generational': 'override',
    },
    'ira-clean-energy-extend': {
        'direction': 'derived:deficit_sign',
        'progressivity': 'fallback:credit_repeal',
        'govt_size': 'derived:direction',
        'base': 'override',
        'generational': 'override',
    },
}

__all__ = ["POLICY_TAGS", "TAG_SOURCES"]
